import unittest

from financial_extractor import _heading_score, parse_financial_number
from financial_models import StatementScope, StatementType
from metric_aliases import CANONICAL_METRICS, resolve_metric
from pdf_parser import PdfPage
from table_extractor import detect_unit


class ReportLayoutRegression(unittest.TestCase):
    def test_summary_chinese_statements_and_local_contents(self):
        headings = [
            ('概要合并利润及其他综合收益表', StatementType.INCOME_STATEMENT),
            ('概要合并财务状况表', StatementType.BALANCE_SHEET),
            ('概要合并现金流量表', StatementType.CASH_FLOW),
        ]
        for heading, expected in headings:
            result = _heading_score(PdfPage(1, heading + '\n人民币百万元\n2025年\n2024年', 80))
            self.assertEqual(result['statement_type'], expected)
            self.assertEqual(result['scope'], StatementScope.CONSOLIDATED)
        contents = '\n'.join(line for heading, _ in headings for line in (heading, '68'))
        self.assertIsNone(_heading_score(PdfPage(1, contents, len(contents)))['statement_type'])

    def test_plural_english_headings_and_dollar_scale(self):
        for heading, expected in [
            ('CONSOLIDATED STATEMENTS OF OPERATIONS', StatementType.INCOME_STATEMENT),
            ('CONSOLIDATED BALANCE SHEETS', StatementType.BALANCE_SHEET),
            ('CONSOLIDATED STATEMENTS OF CASH FLOWS', StatementType.CASH_FLOW),
        ]:
            result = _heading_score(PdfPage(1, heading + '\n2025\n2024\nTotal assets', 70))
            self.assertEqual(result['statement_type'], expected)
            self.assertEqual(result['scope'], StatementScope.CONSOLIDATED)
        unit = detect_unit('(In millions, except number of shares in thousands)\n$ 416,161')
        self.assertEqual((unit.currency, unit.multiplier), ('USD', 1_000_000))
        self.assertEqual(parse_financial_number('$ 35,934').value, 35934)

    def test_source_subtotal_aliases(self):
        for label, canonical in [
            ('销售毛利', 'gross_profit'),
            ('Total net sales', 'revenue'),
            ('Total cost of sales', 'cost_of_revenue'),
            ('Cash generated by operating activities', 'operating_cash_flow'),
        ]:
            self.assertEqual(resolve_metric(label, CANONICAL_METRICS)[0], canonical)


if __name__ == '__main__':
    unittest.main()
